[package]
name = "rust-grpc-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.8.0"
tokio = { version = "1.18.0", features = ["macros", "rt-multi-thread"] }
prost = "0.11.0"
tonic-reflection = "0.5.0"

[build-dependencies]
tonic-build = "0.8.0"
